defmodule Mixduty.OnCalls do
  import Mixduty
  @path "oncalls"

  @moduledoc """
  An on-call represents a contiguous unit of time for which a user will be on call for a given escalation policy and escalation rule. This may be the result of that user always being on call for the escalation rule, or a block of time during which the computed result of a schedule on that escalation rule puts the user on call.

  During an on-call, the user is expected to bear responsibility for responding to any notifications he or she receives and working to resolve the associated incident(s).

  On-calls cannot be created directly through the API; they are the computed result of how escalation policies and schedules are configured. The API provides read-only access to the on-calls generated by PagerDuty.

  """

  @doc """
  List On-Calls
  #### Example
      Mixduty.OnCalls.list(client)
  """
  def list(client, params \\ [], options \\ []) do
    get("#{@path}", client, params, options)
  end
end
